export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
export const PRODUCT_ADD = "PRODUCT_ADD";

export const CATEGORY_GET_ALL_WITH_API = "CATEGORY_GET_ALL_WITH_API";
export const CATEGORY_START_FETCH = "CATEGORY_START_FETCH";
export const CATEGORY_SUCCESS_FETCH = "CATEGORY_SUCCESS_FETCH";
export const CATEGORY_ERROR_FETCH = "CATEGORY_ERROR_FETCH";

